ejabberd:
  image: rroemhild/ejabberd
  ports:
    - 5222:5222
    - 5269:5269
    - 5280:5280
  environment:
    - ERLANG_NODE=ejabberd
    - XMPP_DOMAIN=garasiku.co.id garasiku.co.id
    - EJABBERD_ADMINS=admin@garasiku.co.id
    - EJABBERD_USERS=admin@garasiku.co.id:admin123 user1@xyz.io
